spring.application.name=school-ba
logging.pattern.console=${CONSOLE_LOG_PATTERN:%green(%d{HH:mm:ss.SSS}) %blue(%-5level) %red([%thread]) %yellow(%logger{15}) - %cyan(%msg%n)}
spring.datasource.url=${SPRING_DATASOURCE_URL:jdbc:postgresql://localhost:5432/school_db}
spring.datasource.username=${SPRING_DATASOURCE_USERNAME:elven_user}
spring.datasource.password=${SPRING_DATASOURCE_PASSWORD:elven_password}
spring.datasource.driver-class-name=org.postgresql.Driver
