package com.elvencode.schoolba.auth.entity;

import java.time.LocalDateTime;
import java.util.UUID;

import com.elvencode.schoolba.audit.entity.BaseEntity;
import com.elvencode.schoolba.auth.enums.IdentityStatus;
import jakarta.persistence.Column;
import jakarta.persistence.Entity;
import jakarta.persistence.EnumType;
import jakarta.persistence.Enumerated;
import jakarta.persistence.GeneratedValue;
import jakarta.persistence.GenerationType;
import jakarta.persistence.Id;
import jakarta.persistence.Table;
import jakarta.validation.constraints.NotBlank;
import jakarta.validation.constraints.NotNull;
import jakarta.validation.constraints.Size;
import lombok.Getter;
import lombok.NoArgsConstructor;
import lombok.Setter;
import lombok.ToString;
import org.hibernate.annotations.DynamicInsert;
import org.hibernate.annotations.DynamicUpdate;

/**
 * A login account. Holds credentials and account state only: who the person is lives
 * in the staff, learner or platform operator record this row points at, and exactly
 * one of those three links is set.
 *
 * <p>The person links are mapped as plain identifiers rather than associations. The
 * authenticated principal needs only the ids, so an association would lazily load a
 * whole person on every sign-in for nothing, and would make this package depend on
 * the learner and staff packages that {@code auth/AGENTS.md} keeps it away from.
 */
@Entity
@Table(name = "m_identity")
@DynamicInsert
@DynamicUpdate
@Getter
@Setter
@NoArgsConstructor
@ToString(onlyExplicitlyIncluded = true)
public class Identity extends BaseEntity {

    private static final int USERNAME_MAX_LENGTH = 64;
    private static final int PHONE_NUMBER_MAX_LENGTH = 32;
    private static final int PHONE_NUMBER_E164_MAX_LENGTH = 16;
    private static final int PASSWORD_HASH_MAX_LENGTH = 255;
    private static final int DISPLAY_NAME_MAX_LENGTH = 160;
    private static final int STATUS_MAX_LENGTH = 32;

    @Id
    @GeneratedValue(strategy = GenerationType.UUID)
    @ToString.Include
    private UUID id;

    /** Owning school. Absent only for a platform operator, who belongs to no school. */
    @Column(name = "school_id")
    private UUID schoolId;

    /** Set only for a platform operator's login. */
    @Column(name = "platform_operator_id")
    private UUID platformOperatorId;

    /** Set only for a staff member's login. */
    @Column(name = "staff_id")
    private UUID staffId;

    /** Set only for a learner's login. Drives every {@code -own} permission check. */
    @Column(name = "learner_id")
    private UUID learnerId;

    /**
     * Generated by the database as {@code learner_id IS NULL}, so it means "not a
     * learner" and is true for a platform operator too. Never written from here:
     * PostgreSQL rejects an insert or update that supplies a generated column.
     */
    @Column(name = "is_staff", insertable = false, updatable = false)
    private Boolean staff;

    /** The only login identifier. Stored lower case; fold input before looking it up. */
    @NotBlank
    @Size(max = USERNAME_MAX_LENGTH)
    @Column(name = "username", nullable = false, length = USERNAME_MAX_LENGTH, unique = true)
    @ToString.Include
    private String username;

    @NotBlank
    @Size(max = PHONE_NUMBER_MAX_LENGTH)
    @Column(name = "phone_number", nullable = false, length = PHONE_NUMBER_MAX_LENGTH)
    private String phoneNumber;

    /** Normalized form. The account's recovery channel, unique within the school. */
    @NotBlank
    @Size(max = PHONE_NUMBER_E164_MAX_LENGTH)
    @Column(name = "phone_number_e164", nullable = false, length = PHONE_NUMBER_E164_MAX_LENGTH)
    private String phoneNumberE164;

    /**
     * BCrypt hash, or null until the account is activated. Callers must reject a null
     * hash rather than hand it to the password encoder.
     */
    @Size(max = PASSWORD_HASH_MAX_LENGTH)
    @Column(name = "password_hash", length = PASSWORD_HASH_MAX_LENGTH)
    private String passwordHash;

    /** Label for the user interface. The person record owns the legal name. */
    @NotBlank
    @Size(max = DISPLAY_NAME_MAX_LENGTH)
    @Column(name = "display_name", nullable = false, length = DISPLAY_NAME_MAX_LENGTH)
    private String displayName;

    @NotNull
    @Enumerated(EnumType.STRING)
    @Column(name = "status", nullable = false, length = STATUS_MAX_LENGTH)
    @ToString.Include
    private IdentityStatus status = IdentityStatus.PENDING_ACTIVATION;

    /**
     * Change counter for cached permission sets, maintained by database triggers on
     * every grant change.
     *
     * <p>Read-only on purpose, and deliberately not a JPA {@code @Version}. Mapping it
     * as writable would let an entity loaded before a grant change write its stale
     * value back and silently undo a permission invalidation, which fails quietly:
     * nothing errors, the account simply keeps access it no longer has.
     */
    @Column(name = "authorization_version", insertable = false, updatable = false)
    private int authorizationVersion;

    @Column(name = "failed_attempt_count", nullable = false)
    private short failedAttemptCount;

    /** Null when the account is not locked out. */
    @Column(name = "locked_until")
    private LocalDateTime lockedUntil;

    @Column(name = "last_login_at")
    private LocalDateTime lastLoginAt;

    @Column(name = "password_changed_at", nullable = false)
    private LocalDateTime passwordChangedAt;

    /**
     * Whether this account may authenticate right now. Active alone is not enough: an
     * account can be active and still serving a lockout from failed attempts.
     */
    public boolean isEligibleToAuthenticate() {
        return status == IdentityStatus.ACTIVE
                && passwordHash != null
                && !isLockedOut();
    }

    public boolean isLockedOut() {
        return lockedUntil != null && lockedUntil.isAfter(LocalDateTime.now());
    }

    /** True when this login belongs to a learner, which is what {@code -own} resolves against. */
    public boolean isLearner() {
        return learnerId != null;
    }
}
